# Linear Algebra Operations (NumPy `np.linalg`)

Understand matrix representation, matrix multiplication methods, common vector operations, matrix properties, solving linear systems, eigenvalues/eigenvectors, SVD, and norms.


## Matrix Representation — `np.array` vs `np.matrix`

In [2]:
import numpy as np

A_array = np.array([[1, 2], [3, 4]])
A_matrix = np.matrix([[1, 2], [3, 4]])

print('array type:', type(A_array))
print('matrix type:', type(A_matrix))

# Recommended modern usage:
# prefer np.array over np.matrix


array type: <class 'numpy.ndarray'>
matrix type: <class 'numpy.matrix'>


## Matrix Multiplication — `dot`, `matmul`, `@`, `einsum`

In [3]:
A = np.array([[1, 2, 3],
               [4, 5, 6]])      # shape (2,3)
B = np.array([[1, 2],
               [3, 4],
               [5, 6]])         # shape (3,2)

print('dot:\n', np.dot(A, B))
print('matmul:\n', np.matmul(A, B))
print('@ operator:\n', A @ B)
print('einsum:\n', np.einsum('ij,jk->ik', A, B))

dot:
 [[22 28]
 [49 64]]
matmul:
 [[22 28]
 [49 64]]
@ operator:
 [[22 28]
 [49 64]]
einsum:
 [[22 28]
 [49 64]]


## Cross Product, Inner Product, Outer Product

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print('cross:', np.cross(v1, v2))
print('inner:', np.inner(v1, v2))
print('outer:\n', np.outer(v1, v2))

cross: [-3  6 -3]
inner: 32
outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Transpose, Determinant, and Inverse

In [5]:
M = np.array([[2, 1],
               [5, 3]])

print('Transpose:\n', np.transpose(M))
print('Determinant:', np.linalg.det(M))
print('Inverse:\n', np.linalg.inv(M))

Transpose:
 [[2 5]
 [1 3]]
Determinant: 1.0000000000000009
Inverse:
 [[ 3. -1.]
 [-5.  2.]]


## Solving Linear Equations — `np.linalg.solve`

In [6]:
# Solve Mx = b
M = np.array([[2, 1],
               [5, 3]])
b = np.array([1, 2])

x = np.linalg.solve(M, b)
print('Solution x:', x)

# Validate solution
print('Check Mx:', M @ x)

Solution x: [ 1. -1.]
Check Mx: [1. 2.]


## Eigenvalues and Eigenvectors — `np.linalg.eig`

In [7]:
A = np.array([[4, 1],
               [2, 3]])

eigvals, eigvecs = np.linalg.eig(A)

print('Eigenvalues:', eigvals)
print('Eigenvectors (columns):\n', eigvecs)

# Verification: A v = λ v
v = eigvecs[:, 0]
λ = eigvals[0]
print('\nCheck A @ v:', A @ v)
print('Check λ * v:', λ * v)

Eigenvalues: [5. 2.]
Eigenvectors (columns):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

Check A @ v: [3.53553391 3.53553391]
Check λ * v: [3.53553391 3.53553391]


## Singular Value Decomposition — `np.linalg.svd`

In [8]:
M = np.array([[1, 2, 3],
               [4, 5, 6]])

U, S, VT = np.linalg.svd(M)

print('U:\n', U)
print('Singular values:', S)
print('V^T:\n', VT)

# Reconstruct
M_reconstructed = U @ np.diag(S) @ VT
print('\nReconstructed:\n', M_reconstructed)

U:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular values: [9.508032   0.77286964]
V^T:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## Norms — `np.linalg.norm`

In [ ]:
v = np.array([3, 4])

print('L2 norm:', np.linalg.norm(v))
print('L1 norm:', np.linalg.norm(v, 1))
print('Infinity norm:', np.linalg.norm(v, np.inf))