# Array Joining and Splitting



## Concatenation — `np.concatenate`, `hstack`, `vstack`, `dstack`

In [1]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

c0 = np.concatenate((a, b), axis=0)
c1 = np.concatenate((a, b), axis=1)

print('concatenate axis=0:\n', c0)
print('\nconcatenate axis=1:\n', c1)

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [2]:
h = np.hstack((a, b))
v = np.vstack((a, b))

print('hstack:\n', h)
print('\nvstack:\n', v)

hstack:
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
d = np.dstack((a, b))
print('dstack shape:', d.shape)
print(d)

dstack shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## Stacking — `column_stack`, `row_stack`

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

col = np.column_stack((x, y))
row = np.row_stack((x, y))

print('column_stack:\n', col)
print('\nrow_stack:\n', row)

column_stack:
 [[1 4]
 [2 5]
 [3 6]]

row_stack:
 [[1 2 3]
 [4 5 6]]


C:\Users\DELL\AppData\Local\Temp\ipykernel_5680\232705570.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  row = np.row_stack((x, y))


## Splitting — `split`, `hsplit`, `vsplit`, `array_split`

In [5]:
M = np.arange(1, 13).reshape(3, 4)
print('M:\n', M)

s = np.split(M, 2, axis=1)
print('\nsplit(M,2,axis=1):')
for block in s:
    print(block)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

split(M,2,axis=1):
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [6]:
hs = np.hsplit(M, 2)
vs = np.vsplit(M, 3)

print('hsplit result:', hs)
print('vsplit result:', vs)

hsplit result: [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
vsplit result: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [7]:
asplit = np.array_split(M, 3, axis=1)
print('array_split into 3 column groups:')
for block in asplit:
    print(block)

array_split into 3 column groups:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]
