# Broadcasting & Vectorization Patterns

Understand how NumPy broadcasting works and how to use vectorized operations instead of loops.


## Broadcasting Rules

Two dimensions are compatible if:
- They are equal, or
- One of them is 1

Shapes are compared from **right to left**.


In [2]:
import numpy as np

a = np.array([1, 2, 3])     
b = 5                     
print(a + b)                

[6 7 8]


## Row and Column Broadcasting

In [ ]:
col = np.array([[1],[2],[3]])   
row = np.array([10,20,30])       
row2 = row.reshape(1,3)        

print(col + row2)              

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Replacing Loops with Vectorization

In [4]:
# Without vectorization
x = np.arange(10)
y_loop = []
for v in x:
    y_loop.append(v**2)
y_loop = np.array(y_loop)

# With vectorization
y_vec = x**2

print('loop result:', y_loop)
print('vectorized:', y_vec)

loop result: [ 0  1  4  9 16 25 36 49 64 81]
vectorized: [ 0  1  4  9 16 25 36 49 64 81]


## Pairwise Differences Using Broadcasting

In [5]:
v = np.array([1, 4, 9])
pairwise_diff = v[:, None] - v[None, :]
print(pairwise_diff)

[[ 0 -3 -8]
 [ 3  0 -5]
 [ 8  5  0]]


## Expanding Dimensions for Broadcasting

In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20])

X = x[:, None]   # (3,1)
Y = y[None, :]   # (1,2)

print('result shape:', (X+Y).shape)
print(X+Y)

result shape: (3, 2)
[[11 21]
 [12 22]
 [13 23]]


## Common Broadcasting Pitfalls

In [7]:
A = np.ones((3,2))
B = np.ones((3,))   # shape (3,)

try:
    A + B
except ValueError as e:
    print("Error:", e)

# Fix by reshaping B
B2 = B.reshape(3,1)
print(A + B2)

Error: operands could not be broadcast together with shapes (3,2) (3,) 
[[2. 2.]
 [2. 2.]
 [2. 2.]]
