# Array Creation

---
## From Scratch

### Using `np.array()`, `np.empty()`, `np.zeros()`, `np.ones()`

In [1]:
import numpy as np

# Create array from list
a = np.array([1, 2, 3])

# Create empty array (uninitialized values)
b = np.empty((2, 3))

# Create array of zeros
c = np.zeros((2, 3))

# Create array of ones
d = np.ones((2, 3))

print('array():\n', a)
print('\nempty():\n', b)
print('\nzeros():\n', c)
print('\nones():\n', d)

array():
 [1 2 3]

empty():
 [[ 7.07100575e+194  6.02182992e+151  8.06409165e-310]
 [-1.56125113e-017  2.95902366e-312  1.41544249e-307]]

zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]

ones():
 [[1. 1. 1.]
 [1. 1. 1.]]


### Using `np.full()`, `np.eye()`, `np.identity()`

In [2]:
# Create array filled with a specific value
full_arr = np.full((2, 3), 7)

# Create identity matrix
eye_arr = np.eye(3)
identity_arr = np.identity(4)

print('full():\n', full_arr)
print('\neye():\n', eye_arr)
print('\nidentity():\n', identity_arr)

full():
 [[7 7 7]
 [7 7 7]]

eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

identity():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Using `np.arange()`, `np.linspace()`, `np.logspace()`

In [3]:
# Create sequences
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)
logspace_arr = np.logspace(1, 3, 4)

print('arange():', arange_arr)
print('linspace():', linspace_arr)
print('logspace():', logspace_arr)

arange(): [0 2 4 6 8]
linspace(): [0.   0.25 0.5  0.75 1.  ]
logspace(): [  10.           46.41588834  215.443469   1000.        ]


### Using `np.meshgrid()`

In [4]:
x = np.arange(3)
y = np.arange(3)
X, Y = np.meshgrid(x, y)

print('X:\n', X)
print('Y:\n', Y)

X:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]
Y:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


### Using `np.fromfunction()`

In [5]:
# Create array from function
f = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(f)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Using `np.fromiter()`

In [ ]:
# Create array from iterator
iterable = (x * x for x in range(5))
arr = np.fromiter(iterable, dtype=int)
print(arr)

## Random Arrays

NumPy has a powerful `random` module for generating random data.

### Using `np.random.random()`

In [6]:
rand_arr = np.random.random((2, 3))
print(rand_arr)

[[0.11406777 0.86901935 0.62631982]
 [0.29379912 0.79861554 0.84785571]]


### Using `np.random.rand()` and `np.random.randn()`

In [7]:
rand_arr2 = np.random.rand(2, 3)  # Uniform distribution [0,1)
randn_arr = np.random.randn(2, 3)  # Standard normal distribution

print('rand():\n', rand_arr2)
print('\nrandn():\n', randn_arr)

rand():
 [[0.36133434 0.69969619 0.15468106]
 [0.02618402 0.02464759 0.65853589]]

randn():
 [[-0.90776619 -0.10908828  0.70557785]
 [ 0.6700813  -0.25118118 -1.45806341]]


### Using `np.random.randint()`

In [8]:
randint_arr = np.random.randint(0, 10, (2, 3))
print(randint_arr)

[[9 8 9]
 [3 2 2]]


### Using `np.random.choice()`

In [9]:
choice_arr = np.random.choice([1, 2, 3, 4, 5], size=(2, 3))
print(choice_arr)

[[2 4 5]
 [3 3 5]]


### Using `np.random.seed()`

In [10]:
np.random.seed(42)
print('Seeded random array:', np.random.rand(3))

Seeded random array: [0.37454012 0.95071431 0.73199394]


### Using `np.random.shuffle()` and `np.random.permutation()`

In [11]:
arr = np.arange(10)
np.random.shuffle(arr)
print('Shuffled:', arr)

perm_arr = np.random.permutation(10)
print('Permutation:', perm_arr)

Shuffled: [9 7 0 3 5 8 2 1 6 4]
Permutation: [0 8 6 3 1 4 5 2 9 7]
