# Statistical and Mathematical Operations

Understand common statistical, correlation, percentile, and histogram operations.

## Descriptive Statistics

In [2]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print('mean:', np.mean(data))
print('median:', np.median(data))
print('average:', np.average(data))
print('std:', np.std(data))
print('var:', np.var(data))
print('ptp (peak-to-peak):', np.ptp(data))

mean: 30.0
median: 30.0
average: 30.0
std: 14.142135623730951
var: 200.0
ptp (peak-to-peak): 40


In [3]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('M:\n', M)
print('mean axis=0 (column means):', np.mean(M, axis=0))
print('mean axis=1 (row means):', np.mean(M, axis=1))

M:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mean axis=0 (column means): [4. 5. 6.]
mean axis=1 (row means): [2. 5. 8.]


## Correlation and Covariance

In [4]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

corr = np.corrcoef(x, y)
cov = np.cov(x, y)

print('corrcoef:\n', corr)
print('\ncov:\n', cov)

corrcoef:
 [[1. 1.]
 [1. 1.]]

cov:
 [[ 2.5  5. ]
 [ 5.  10. ]]


## Percentiles and Quantiles

In [5]:
arr = np.array([5,1,7,9,3,8])
print('25th percentile:', np.percentile(arr, 25))
print('50th percentile (median):', np.percentile(arr, 50))
print('quantile 0.75:', np.quantile(arr, 0.75))

25th percentile: 3.5
50th percentile (median): 6.0
quantile 0.75: 7.75


## Histograms

In [6]:
data = np.random.randint(0, 20, size=50)
hist, bin_edges = np.histogram(data, bins=5)

print('hist:', hist)
print('bin_edges:', bin_edges)

hist: [10 10 10 12  8]
bin_edges: [ 0.   3.8  7.6 11.4 15.2 19. ]


In [7]:
# 2D histogram
x = np.random.randn(1000)
y = np.random.randn(1000) * 2 + 1

hist2d, xedges, yedges = np.histogram2d(x, y, bins=5)
print('hist2d:\n', hist2d)
print('xedges:', xedges)
print('yedges:', yedges)

hist2d:
 [[  5.  16.  25.  17.   1.]
 [ 11.  73. 126.  60.  11.]
 [ 18. 143. 197. 106.  10.]
 [ 11.  31.  79.  42.   2.]
 [  0.   3.   9.   3.   1.]]
xedges: [-2.89807853 -1.61535599 -0.33263346  0.95008908  2.23281162  3.51553416]
yedges: [-4.66577368e+00 -2.33256596e+00  6.41763746e-04  2.33384949e+00
  4.66705721e+00  7.00026493e+00]
