# NumPy Random Module

Random sampling, probability distributions, shuffling, and the modern random generator API.


## Random Sampling

In [2]:
import numpy as np

u = np.random.random(5)       
n = np.random.randn(5)     

print('uniform:', u)
print('normal:', n)

uniform: [0.93639833 0.51489128 0.58339823 0.67545149 0.36074964]
normal: [ 1.86349433 -0.17847724  0.29416665  1.20141116  1.48750654]


## Common Distributions

In [3]:
uni = np.random.uniform(2, 5, size=5)
norm = np.random.normal(10, 2, size=5)
binom = np.random.binomial(10, 0.3, size=5)
pois = np.random.poisson(3, size=5)
exp = np.random.exponential(2.0, size=5)

print('uniform(2,5):', uni)
print('normal(10,2):', norm)
print('binomial:', binom)
print('poisson:', pois)
print('exponential:', exp)

uniform(2,5): [2.66774342 3.6832222  4.49293104 3.81410449 3.15314968]
normal(10,2): [13.55227784  9.37063967  8.94820251  8.96853542  8.96606052]
binomial: [5 5 4 6 3]
poisson: [2 4 2 5 1]
exponential: [2.41341984 1.56832482 2.87150363 6.39133902 1.2635128 ]


## Random Integers — `randint`

In [4]:
ri = np.random.randint(0, 10, size=(2,3))
print(ri)

[[0 8 2]
 [3 0 3]]


## Random Choice

In [5]:
print(np.random.choice([10,20,30,40], size=6, replace=True))
print(np.random.choice([1,2,3,4], size=3, replace=False))

[20 20 30 10 30 30]
[1 3 4]


## Shuffling and Permutation

In [6]:
arr = np.arange(10)
np.random.shuffle(arr)   # in-place
print('shuffle:', arr)

p = np.random.permutation(10)
print('permutation:', p)

shuffle: [8 0 2 9 4 3 1 6 7 5]
permutation: [2 6 0 8 1 5 7 9 3 4]


## Random Seed

In [7]:
np.random.seed(42)
print(np.random.rand(4))

[0.37454012 0.95071431 0.73199394 0.59865848]


## Random Generator API — `default_rng()`

In [8]:
rng = np.random.default_rng(seed=123)
print(rng.uniform(0,1,5))
print(rng.normal(0,1,5))
print(rng.integers(0,10,5))

[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[ 0.57710379 -0.63646365  0.54195222 -0.31659545 -0.32238912]
[0 5 2 2 2]
