# NumPy Array Operations 

arithmetic, broadcasting, comparisons, logical ops, conditionals, math functions, rounding, reductions, and extrema.



## 1) Arithmetic Operations (Element-wise)

Operations act element-wise for arrays of the **same shape**, or broadcastable shapes.


In [2]:
import numpy as np

a = np.array([1, 2, 3], dtype=float)
b = np.array([4, 5, 6], dtype=float)

print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)
print('a / b:', a / b)  # beware division by zero in general

a + b: [5. 7. 9.]
a - b: [-3. -3. -3.]
a * b: [ 4. 10. 18.]
a / b: [0.25 0.4  0.5 ]


### Power and Modulus

In [3]:
print('a ** 2:', a ** 2)
print('b % 4:', b % 4)  # remainder (modulus)

a ** 2: [1. 4. 9.]
b % 4: [0. 1. 2.]


**Pitfall:** Integer division vs float division  
NumPy follows Python 3 rules: `/` is float division. Use `//` for floor division.


In [4]:
x = np.array([5, 7, 9])
y = np.array([2, 2, 2])
print('x / y:', x / y)   # float
print('x // y:', x // y) # floor integer division

x / y: [2.5 3.5 4.5]
x // y: [2 3 4]


## 2) Broadcasting — Rules & Intuition

**Rule:** Align shapes from **right to left**. Two dims are compatible if **equal** or **one is 1**.  
NumPy virtually **stretches** axes with size 1 without copying data.


In [5]:
# Scalar with vector
v = np.array([1, 2, 3])
print('v + 10 ->', v + 10)  # scalar broadcast

# Column (3,1) with row (1,4) -> (3,4)
col = np.array([[1],[2],[3]])
row = np.array([[10,20,30,40]])
C = col + row
print('C shape:', C.shape)
print(C)

v + 10 -> [11 12 13]
C shape: (3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


**Incompatible shapes error**

In [6]:
A = np.ones((3,2))
B = np.ones((3,))  # shape (3,)
try:
    A + B
except ValueError as e:
    print('Error:', e)

# Fix via reshape to align trailing axes
B2 = B.reshape(3,1)        # (3,1)
print('A + B2 shape:', (A + B2).shape)

Error: operands could not be broadcast together with shapes (3,2) (3,) 
A + B2 shape: (3, 2)


**Broadcasting in practice: centering columns**

In [7]:
M = np.arange(12, dtype=float).reshape(3,4)
col_means = M.mean(axis=0, keepdims=True)  # shape (1,4)
centered = M - col_means                   # broadcast subtraction
print('M:\n', M)
print('\nColumn means:', col_means)
print('\nCentered:\n', centered)

M:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

Column means: [[4. 5. 6. 7.]]

Centered:
 [[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]


## 3) Comparison Operations (Element-wise)

Return boolean arrays that can be used for masking or counting.


In [8]:
arr = np.array([1, 3, 3, 7, 9])
print('arr > 3:', arr > 3)
print('arr == 3:', arr == 3)
print('arr != 3:', arr != 3)
print('Count of >3:', np.sum(arr > 3))

arr > 3: [False False False  True  True]
arr == 3: [False  True  True False False]
arr != 3: [ True False False  True  True]
Count of >3: 2


## 4) Logical Operations

- `np.logical_and(A, B)`  
- `np.logical_or(A, B)`  
- `np.logical_not(A)`  


In [9]:
x = np.array([1,2,3,4,5])
cond1 = x > 2
cond2 = x % 2 == 0

print('cond1:', cond1)
print('cond2:', cond2)
print('and:', np.logical_and(cond1, cond2))
print('or :', np.logical_or(cond1, cond2))
print('not cond1:', np.logical_not(cond1))

cond1: [False False  True  True  True]
cond2: [False  True False  True False]
and: [False False False  True False]
or : [False  True  True  True  True]
not cond1: [ True  True False False False]


## 5) Conditional Selection — `np.where()` & Boolean Masking

- `np.where(cond, A, B)` selects element from `A` where cond is True, else from `B`.
- Boolean masking: `x[cond]` filters elements.


In [10]:
scores = np.array([35, 62, 47, 90, 51])
labels = np.where(scores >= 60, 'Pass', 'Fail')
print('labels:', labels)

mask = scores >= 50
print('mask:', mask)
print('scores[mask]:', scores[mask])

labels: ['Fail' 'Pass' 'Fail' 'Pass' 'Fail']
mask: [False  True False  True  True]
scores[mask]: [62 90 51]


**Multi-output where:** e.g., z-score thresholding

In [11]:
data = np.array([10., 11., 12., 200., 13., 12., 11.])
mu = data.mean()
sigma = data.std()
z = (data - mu) / sigma
flagged = np.where(np.abs(z) > 2.5, 'Outlier', 'OK')
print('z:', z)
print('flagged:', flagged)

z: [-0.43095    -0.41579096 -0.40063191  2.4492686  -0.38547287 -0.40063191
 -0.41579096]
flagged: ['OK' 'OK' 'OK' 'OK' 'OK' 'OK' 'OK']


## 6) Mathematical Functions

Vectorized ufuncs are fast (implemented in C).

In [12]:
a = np.array([1., 2., 3., 4.])
print('np.add(a,5):', np.add(a,5))
print('np.subtract(a,2):', np.subtract(a,2))
print('np.multiply(a,3):', np.multiply(a,3))
print('np.divide(a,2):', np.divide(a,2))

np.add(a,5): [6. 7. 8. 9.]
np.subtract(a,2): [-1.  0.  1.  2.]
np.multiply(a,3): [ 3.  6.  9. 12.]
np.divide(a,2): [0.5 1.  1.5 2. ]


In [13]:
print('exp:', np.exp(a))
print('log:', np.log(a))     # ln
print('sqrt:', np.sqrt(a))

exp: [ 2.71828183  7.3890561  20.08553692 54.59815003]
log: [0.         0.69314718 1.09861229 1.38629436]
sqrt: [1.         1.41421356 1.73205081 2.        ]


### Trigonometric Functions (angles in radians)

In [14]:
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
print('sin:', np.sin(angles))
print('cos:', np.cos(angles))
print('tan:', np.tan(angles))  # beware pi/2 etc -> huge values

sin: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
cos: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]


### Rounding Functions

In [15]:
vals = np.array([1.2, 3.7, 2.5, -1.3, -2.5])
print('ceil :', np.ceil(vals))
print('floor:', np.floor(vals))
print('round:', np.round(vals))  # bankers rounding to even in NumPy

ceil : [ 2.  4.  3. -1. -2.]
floor: [ 1.  3.  2. -2. -3.]
round: [ 1.  4.  2. -1. -2.]


## 7) Reductions: Sum, Product, Cumulative

You can compute across the whole array or along an axis.


In [16]:
b = np.array([[1,2,3],
               [4,5,6]], dtype=float)

print('sum all     :', np.sum(b))
print('sum axis=0  :', np.sum(b, axis=0))  # column sums
print('sum axis=1  :', np.sum(b, axis=1))  # row sums

print('prod all    :', np.prod(b))
print('cumsum axis=1:', np.cumsum(b, axis=1))
print('cumprod axis=0:\n', np.cumprod(b, axis=0))

sum all     : 21.0
sum axis=0  : [5. 7. 9.]
sum axis=1  : [ 6. 15.]
prod all    : 720.0
cumsum axis=1: [[ 1.  3.  6.]
 [ 4.  9. 15.]]
cumprod axis=0:
 [[ 1.  2.  3.]
 [ 4. 10. 18.]]


**Keep dimensions with `keepdims=True` (useful for broadcasting)**

In [17]:
col_sum = b.sum(axis=0, keepdims=True)  # shape (1,3)
print('col_sum shape:', col_sum.shape)
normed = b / col_sum                      # broadcast divide by column sums
print('normed:\n', normed)

col_sum shape: (1, 3)
normed:
 [[0.2        0.28571429 0.33333333]
 [0.8        0.71428571 0.66666667]]


## 8) Min/Max & Indices (`min`, `max`, `argmin`, `argmax`)

In [18]:
c = np.array([[12,  5,  7],
               [30,  2, 11]])

print('min all  :', c.min())
print('max all  :', c.max())
print('argmin all (flat index):', c.argmin())
print('argmax all (flat index):', c.argmax())

print('min axis=0:', c.min(axis=0))  # column-wise minima
print('max axis=1:', c.max(axis=1))  # row-wise maxima

# Retrieve coordinates of max using unravel_index
max_idx = np.argmax(c)
coords = np.unravel_index(max_idx, c.shape)
print('max coords:', coords, 'value:', c[coords])

min all  : 2
max all  : 30
argmin all (flat index): 4
argmax all (flat index): 3
min axis=0: [12  2  7]
max axis=1: [12 30]
max coords: (np.int64(1), np.int64(0)) value: 30


### NaN-safe reductions (bonus)

Use `np.nan*` variants to ignore NaNs: `np.nanmin`, `np.nanmax`, `np.nansum`, etc.


In [19]:
d = np.array([1., np.nan, 3., 5.])
print('sum    :', np.sum(d))      # -> nan (propagates)
print('nansum :', np.nansum(d))   # ignores NaNs
print('nanmin :', np.nanmin(d), 'nanmax:', np.nanmax(d))

sum    : nan
nansum : 9.0
nanmin : 1.0 nanmax: 5.0
